//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserRegistration.Views
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class UserInfo
    {
        public int Id { get; set; }
        [Required]
        [DisplayName("First Name")]
        public string First_Name { get; set; }
        [Required]
        [DisplayName("Last Name")]
        public string Last_Name { get; set; }
        [Required]
        [DisplayName("Address 1")]
        public string Address_1 { get; set; }
        [Required]
        [DisplayName("Address 2")]
        public string Address_2 { get; set; }
        [Required]
        public string City { get; set; }
        [Required]
        public string State { get; set; }
        [Required]
        [StringLength(10)]
        [RegularExpression(@"^\d{5}(-\d{4})?$", ErrorMessage = "Invalid Zip")]
        public string Zip { get; set; }
        [Required]
        public string Country { get; set; }

        public IEnumerable<SelectListItem> States { get; set; }
    }
}
